set cursorline
set tabstop=4
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'Valloric/YouCompleteMe'
Plugin 'ntpeters/vim-better-whitespace'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

" how many chars is needed to triger the completion; default = 2
let g:ycm_min_num_of_chars_for_completion = 1
" enable completion in comment; default = 0
let g:ycm_complete_in_comments = 1
" key-binding about break completion; default = ['<C-y>']
" let g:ycm_key_list_stop_completion = ['<C-y>']

let g:ycm_global_ycm_extra_conf = '~/.vim/bundle/YouCompleteMe/plugin/.ycm_extra_conf.py'

let g:ycm_extra_conf_vim_data = ['&filetype']
